name: Update README

on:
  issue_comment:
    types: created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get latest repo
        uses: actions/checkout@master
      - name: Get JAR
        run: java -jar gh-meme-maker.main.jar
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.THE_GITHUB_ACCESS_TOKEN }}