name: Generate Meme

on:
  issues:
    types: opened
  issue_comment:
    types: created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get JAR
        run: java -jar gh-meme-maker.main.jar
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.THE_GITHUB_ACCESS_TOKEN }}