name: Generate Meme

on:
  issues:
    types: opened
  issue_comment:
    types: created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get latest repo
        uses: actions/checkout@master
      - name: Get JAR
        run: java -jar gh-meme-maker.main.jar "${{github.event.issue.id}}" "${{github.event.comment.id}}"
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.THE_GITHUB_ACCESS_TOKEN }}